name: auto_deploy

on:
  push:
    branches: master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ssh
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          USER: ${{ secrets.USER }}
          HOST: ${{ secrets.HOST }}
        run: | 
            echo "$SECRET_KEY" > secret_key
            chmod 600 secret_key
            ssh -oStrictHostKeyChecking=no pentasunf@sv13024.xserver.jp -p 10022 -i secret_key "cd /home/pentasunf/pentasunf.tech/public_html/3ia3ia/ && sh ./.github/workflows/auto-deploy.sh"
